**Tensors in tensorflow**

In [5]:
import tensorflow as  tf
tensor_zero_d=tf.constant(10)

print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [21]:
tensor_one_d=tf.constant([10,2,4], dtype=tf.float32)
casted_tenosr_1d=tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
casted_tenosr_1d

tf.Tensor([10.  2.  4.], shape=(3,), dtype=float32)


<tf.Tensor: shape=(3,), dtype=int16, numpy=array([10,  2,  4], dtype=int16)>

In [7]:
tensor_2d=tf.constant([
    [1,4,5],
    [2,4,6],
    [3,6,7]
    ])
print(tensor_2d)

tf.Tensor(
[[1 4 5]
 [2 4 6]
 [3 6 7]], shape=(3, 3), dtype=int32)


In [16]:
tensor_3d=tf.constant([
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]]
])

print(tensor_3d)
print(tensor_3d.ndim)
tensor_3d.shape

tf.Tensor(
[[[1 4 5]
  [2 4 6]]

 [[1 5 7]
  [2 5 8]]

 [[3 4 5]
  [4 5 6]]], shape=(3, 2, 3), dtype=int32)
3


TensorShape([3, 2, 3])

In [19]:
tensors_4d=tf.constant([
[
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]],
],
[
    [[1,5,3],
    [2,7,6]],

    [[1,5,0],
    [2,9,8]],

    [[3,6,5],
    [4,2,6]],
],
[
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]],
],
])

print(tensors_4d)

tf.Tensor(
[[[[1 4 5]
   [2 4 6]]

  [[1 5 7]
   [2 5 8]]

  [[3 4 5]
   [4 5 6]]]


 [[[1 5 3]
   [2 7 6]]

  [[1 5 0]
   [2 9 8]]

  [[3 6 5]
   [4 2 6]]]


 [[[1 4 5]
   [2 4 6]]

  [[1 5 7]
   [2 5 8]]

  [[3 4 5]
   [4 5 6]]]], shape=(3, 3, 2, 3), dtype=int32)


__Numpy to tensor__

In [2]:
import numpy as np
np_array=np.array([1,2,3,4,5,6])
print(np_array)

[1 2 3 4 5 6]


In [6]:
array_to_tenor=tf.convert_to_tensor(np_array)
print(array_to_tenor)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


**identity matrix  in tensor**

In [ ]:
#identity matrix
identity_mat=tf.eye(
    num_rows=4,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.float16
)
print(identity_mat,"\n")
#to make it any number
print(2*identity_mat, "\n")
print(3*identity_mat)

#we can also make it bool
identity_mat_bool=tf.eye(
    num_rows=4,
    num_columns=5,
    batch_shape=None,
    dtype=tf.dtypes.bool
)
print("\n",identity_mat_bool)

#batch shape is for num of batches
identity_mat_batches=tf.eye(
    num_rows=4,
    num_columns=5,
    batch_shape=[2], #we can alos pass it a shape like [2,5]
    dtype=tf.dtypes.float16
)
print(f"matrix batches : {"\n"} {identity_mat_batches}","\n")

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]], shape=(4, 5), dtype=float16) 

tf.Tensor(
[[2. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 2. 0.]], shape=(4, 5), dtype=float16) 

tf.Tensor(
[[3. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 3. 0.]], shape=(4, 5), dtype=float16)

 tf.Tensor(
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]], shape=(4, 5), dtype=bool)
matrix batches : 
 [[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]]] 



**Filling the matrices""

In [24]:
fill_mat=tf.fill([2,4],5)
print(fill_mat)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]], shape=(2, 4), dtype=int32)


In [ ]:
#We can also do this for zeros like "tf.zeros"
ones_mat=tf.ones(
    [2,4],
    name=None
)
print(ones_mat)

tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)
