**Tensors in tensorflow**

In [1]:
import tensorflow as  tf
tensor_zero_d=tf.constant(10)

print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [21]:
tensor_one_d=tf.constant([10,2,4], dtype=tf.float32)
casted_tenosr_1d=tf.cast(tensor_one_d, dtype=tf.int16)
print(tensor_one_d)
casted_tenosr_1d

tf.Tensor([10.  2.  4.], shape=(3,), dtype=float32)


<tf.Tensor: shape=(3,), dtype=int16, numpy=array([10,  2,  4], dtype=int16)>

In [7]:
tensor_2d=tf.constant([
    [1,4,5],
    [2,4,6],
    [3,6,7]
    ])
print(tensor_2d)

tf.Tensor(
[[1 4 5]
 [2 4 6]
 [3 6 7]], shape=(3, 3), dtype=int32)


In [16]:
tensor_3d=tf.constant([
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]]
])

print(tensor_3d)
print(tensor_3d.ndim)
tensor_3d.shape

tf.Tensor(
[[[1 4 5]
  [2 4 6]]

 [[1 5 7]
  [2 5 8]]

 [[3 4 5]
  [4 5 6]]], shape=(3, 2, 3), dtype=int32)
3


TensorShape([3, 2, 3])

In [19]:
tensors_4d=tf.constant([
[
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]],
],
[
    [[1,5,3],
    [2,7,6]],

    [[1,5,0],
    [2,9,8]],

    [[3,6,5],
    [4,2,6]],
],
[
    [[1,4,5],
    [2,4,6]],

    [[1,5,7],
    [2,5,8]],

    [[3,4,5],
    [4,5,6]],
],
])

print(tensors_4d)

tf.Tensor(
[[[[1 4 5]
   [2 4 6]]

  [[1 5 7]
   [2 5 8]]

  [[3 4 5]
   [4 5 6]]]


 [[[1 5 3]
   [2 7 6]]

  [[1 5 0]
   [2 9 8]]

  [[3 6 5]
   [4 2 6]]]


 [[[1 4 5]
   [2 4 6]]

  [[1 5 7]
   [2 5 8]]

  [[3 4 5]
   [4 5 6]]]], shape=(3, 3, 2, 3), dtype=int32)
